apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: code
        configMap:
          name: {{ include "backend.fullname" . }}-code
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - pip install flask flask-cors mysql-connector-python && python /app/app.py
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
        envFrom:
        - secretRef:
            name: {{ include "backend.fullname" . }}-secret
        volumeMounts:
        - name: code
          mountPath: /app
