apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.mysql.host | quote }}
  DB_NAME: {{ .Values.mysql.database | quote }}
  DB_USER: {{ .Values.mysql.user | quote }}
  DB_PASSWORD: {{ .Values.mysql.password | quote }}
