image:
  repository: python
  tag: "3.9.21-alpine3.21"
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

mysql:
  host: "mysql"
  database: "tododb"
  user: "todouser"
  password: "todopassword"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2
