apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.auth.database | quote }}
  MYSQL_USER: {{ .Values.auth.user | quote }}
  MYSQL_PASSWORD: {{ .Values.auth.password | quote }}
